@extends('layouts.app')

@section('content')
<style>
  .clearfix::after {
    content: "";
    display: table;
    clear: both;
}
  .content {
    text-align: justify; /* Justifica el texto */
    background-color: #ffffff; /* Color beige claro para el fondo */
    border-right: 5px solid #6F4E37; /* Borde lateral café */
    padding: 20px; /* Espaciado interno */
    margin: 20px 0; /* Espacio arriba y abajo */
    border-radius: 10px; /* Bordes redondeados */
    box-shadow: 3px 3px 10px rgba(0, 0, 0, 0.1); /* Sombra suave */
}

.title {
    color: #6F4E37; /* Color café para el título */
    font-weight: bold;
    text-align: center;
    margin-bottom: 15px;
}
</style>

<h1 class="title">Biografía</h1>
<div id="content-area">
    <div id="node-781" class="node node-type-pagina">
        <div class="node-inner">
  
  <div class="content">
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Jos&eacute; Juli&aacute;n Mart&iacute; P&eacute;rez naci&oacute; en la calle Paula No. 41, La Habana, el 28 de enero de 1853. En 1866 matricula en el Instituto de Segunda Ense&ntilde;anza de La Habana. Ingresa tambi&eacute;n en la clase de Dibujo Elemental en la Escuela Profesional de Pintura y Escultura de La Habana, m&aacute;s conocida como San Alejandro.</p>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">El 4 de octubre de 1869, al pasar una escuadra del Primer Batall&oacute;n de Voluntarios por la calle Industrias No. 122, donde resid&iacute;an los Vald&eacute;s Dom&iacute;nguez, de la vivienda se oyen risas y los voluntarios toman esto como una provocaci&oacute;n. Regresan en la noche y someten la casa a un minucioso registro. Entre la correspondencia encuentran una carta dirigida a Carlos de Castro y Castro, compa&ntilde;ero del colegio que, por haberse alistado como voluntario en el ej&eacute;rcito espa&ntilde;ol para combatir a los independentistas, calificaban de ap&oacute;stata.</p>
<div id="attachment_1295" class="wp-caption alignleft" style="border: 0px; margin-top: 4px; margin-right: 24px; margin-bottom: 20px; padding: 4px; vertical-align: baseline; display: inline; float: left; line-height: 18px; text-align: center; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; width: 167px; max-width: 632px !important; background: rgb(241, 241, 241);"><a href="http://www.josemarti.cu/wp-content/uploads/2014/06/005.jpg" class="fancybox" rel="fancybox" style="border: 0px; vertical-align: baseline; color: rgb(4, 87, 169); background: transparent;"><img class="wp-image-1295" src="http://www.josemarti.cu/wp-content/uploads/2014/06/005-183x300.jpg" alt="005" width="157" style="border-style: none; margin-top: 5px; margin-right: 5px; margin-left: 5px; vertical-align: baseline; max-width: 100%; height: auto; background: transparent;" /></a>
<p class="wp-caption-text" style="border: 0px; margin: 5px 5px 24px; vertical-align: baseline; font-family: Arial; color: rgb(136, 136, 136); font-size: 12px; background: transparent;">Retrato de Mart&iacute; al ser condenado a seis a&ntilde;os de prisi&oacute;n por infidencia.</p>
</div>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Por tal raz&oacute;n, el 21 de octubre de 1869 Mart&iacute; ingresa en la C&aacute;rcel Nacional acusado de infidencia por escribir esa carta, junto a su entra&ntilde;able amigo Ferm&iacute;n Vald&eacute;s Dom&iacute;nguez. El 4 de marzo de 1870, Mart&iacute; fue condenado a seis a&ntilde;os de prisi&oacute;n, pena posteriormente conmutada por el destierro a Isla de Pinos, lugar al que llega el 13 de octubre. El 18 de diciembre sale hacia La Habana y el 15 de enero de 1871, por gestiones realizadas por sus padres, logr&oacute; ser deportado a Espa&ntilde;a. All&aacute; comienza a cursar estudios en las universidades de Madrid y Zaragoza, donde se grad&uacute;a de Licenciado en Derecho Civil y en Filosof&iacute;a y Letras.</p>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">De Espa&ntilde;a se traslada a Par&iacute;s, por breve tiempo.&nbsp;<img class="wp-image-3972 alignright" src="http://www.josemarti.cu/wp-content/uploads/2014/05/Manuel-Mercado.jpg" alt="Manuel Mercado" width="124" style="margin-top: 4px; margin-bottom: 12px; margin-left: 24px; vertical-align: baseline; display: inline; float: right; max-width: 100%; height: auto; background: transparent;" />Pasa por Nueva York y llega a Veracruz el 8 de febrero de 1875, donde se re&uacute;ne con su familia. En M&eacute;xico entabla relaciones con Manuel Mercado y conoce a Carmen Zayas Baz&aacute;n, la cubana que ser&iacute;a su esposa.</p>
<div id="attachment_1522" class="wp-caption alignleft" style="border: 0px; margin-top: 4px; margin-right: 24px; margin-bottom: 20px; padding: 4px; vertical-align: baseline; display: inline; float: left; line-height: 18px; text-align: center; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; width: 310px; max-width: 632px !important; background: rgb(241, 241, 241);"><a href="http://www.josemarti.cu/wp-content/uploads/2014/05/05-Escuela-Normal-de-Varones.jpg" class="fancybox" rel="fancybox" style="border: 0px; vertical-align: baseline; color: rgb(4, 87, 169); background: transparent;"><img class="wp-image-1522 size-medium" src="http://www.josemarti.cu/wp-content/uploads/2014/05/05-Escuela-Normal-de-Varones-300x220.jpg" alt="05-Escuela-Normal-de-Varones" width="300" style="border-style: none; margin-top: 5px; margin-right: 5px; margin-left: 5px; vertical-align: baseline; max-width: 100%; height: auto; background: transparent;" /></a>
<p class="wp-caption-text" style="border: 0px; margin: 5px 5px 24px; vertical-align: baseline; font-family: Arial; color: rgb(136, 136, 136); font-size: 12px; background: transparent;">Escuela Normal para Varones en Guatemala dirigida por el cubano Jos&eacute; Mar&iacute;a Izaguirre.</p>
</div>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Del 2 de enero al 24 de febrero de 1877 estuvo de inc&oacute;gnito en La Habana como Juli&aacute;n P&eacute;rez. Al llegar a Guatemala trabaja en la Escuela Normal Central como catedr&aacute;tico de Literatura y de Historia de la Filosof&iacute;a. Retorna a M&eacute;xico, para contraer matrimonio con Carmen el 20 de diciembre de 1877, regresando a inicios de 1878 a Guatemala.</p>
<div id="attachment_1523" class="wp-caption alignright" style="border: 0px; margin-top: 4px; margin-bottom: 20px; margin-left: 24px; padding: 4px; vertical-align: baseline; display: inline; float: right; line-height: 18px; text-align: center; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; width: 167px; max-width: 632px !important; background: rgb(241, 241, 241);"><a href="http://www.josemarti.cu/wp-content/uploads/2014/05/004.jpg" class="fancybox" rel="fancybox" style="border: 0px; vertical-align: baseline; color: rgb(4, 87, 169); background: transparent;"><img class="wp-image-1523" src="http://www.josemarti.cu/wp-content/uploads/2014/05/004-214x300.jpg" alt="004" width="157" style="border-style: none; margin-top: 5px; margin-right: 5px; margin-left: 5px; vertical-align: baseline; max-width: 100%; height: auto; background: transparent;" /></a>
<p class="wp-caption-text" style="border: 0px; margin: 5px 5px 24px; vertical-align: baseline; font-family: Arial; color: rgb(136, 136, 136); font-size: 12px; background: transparent;">Carmen Zayas-Baz&aacute;n y su hijo Jos&eacute; Francisco.</p>
</div>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Concluida la Guerra del 68 vuelve a Cuba el 31 de agosto de 1878, para radicarse en La Habana, y el 22 de noviembre nace Jos&eacute;<br />
Francisco, su &uacute;nico hijo. Comenz&oacute; sus labores conspirativas figurando entre los fundadores del Club Central Revolucionario Cubano, del cual fue elegido vicepresidente el 18 de marzo de 1879. Posteriormente el Comit&eacute; Revolucionario Cubano, radicado en Nueva York bajo la presidencia del Mayor General Calixto Garc&iacute;a, lo nombr&oacute; subdelegado en la Isla.</p>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">En el bufete de su amigo Don Nicol&aacute;s Azc&aacute;rate conoce a Juan Gualberto G&oacute;mez. Entre el 24 y el 26 de agosto de 1879 se produce un nuevo levantamiento en las cercan&iacute;as de Santiago de Cuba. El 17 de septiembre Mart&iacute; es detenido y deportado nuevamente a Espa&ntilde;a, el 25 de septiembre de 1879, por sus v&iacute;nculos en la Guerra Chiquita. Al llegar a Nueva York, se establece en la casa de hu&eacute;spedes de Manuel Mantilla y su esposa, Carmen Miyares.</p>
<div id="attachment_1303" class="wp-caption alignleft" style="border: 0px; margin-top: 4px; margin-right: 24px; margin-bottom: 20px; padding: 4px; vertical-align: baseline; display: inline; float: left; line-height: 18px; text-align: center; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; width: 173px; max-width: 632px !important; background: rgb(241, 241, 241);"><a href="http://www.josemarti.cu/wp-content/uploads/2014/06/0131.jpg" class="fancybox" rel="fancybox" style="border: 0px; vertical-align: baseline; color: rgb(4, 87, 169); background: transparent;"><img class="wp-image-1303" src="http://www.josemarti.cu/wp-content/uploads/2014/06/0131-225x300.jpg" alt="013" width="163" style="border-style: none; margin-top: 5px; margin-right: 5px; margin-left: 5px; vertical-align: baseline; max-width: 100%; height: auto; background: transparent;" /></a>
<p class="wp-caption-text" style="border: 0px; margin: 5px 5px 24px; vertical-align: baseline; font-family: Arial; color: rgb(136, 136, 136); font-size: 12px; background: transparent;">Cincograf&iacute;a de Mart&iacute; con su hijo Jos&eacute; Francisco, fue hecha probablemente en New York, 1880.</p>
</div>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Mart&iacute; logra traer a su esposa e hijo el 3 de marzo de 1880. Permanecen juntos hasta el 21 de octubre, en que Carmen y Jos&eacute; Francisco regresan a Cuba. Una semana despu&eacute;s result&oacute; electo vocal del Comit&eacute; Revolucionario Cubano, del cual asumi&oacute; la presidencia al sustituir a Calixto, quien hab&iacute;a partido hacia Cuba para incorporarse a la Guerra Chiquita.</p>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Entre 1880 y 1890 Mart&iacute; alcanzar&iacute;a renombre en la Am&eacute;rica a trav&eacute;s de art&iacute;culos y cr&oacute;nicas que enviaba desde Nueva York a importantes peri&oacute;dicos:&nbsp;<i style="border: 0px; vertical-align: baseline; background: transparent;">La Opini&oacute;n Nacional,</i>&nbsp;de Caracas;&nbsp;<i style="border: 0px; vertical-align: baseline; background: transparent;">La Naci&oacute;n,</i>&nbsp;de Buenos Aires y&nbsp;<i style="border: 0px; vertical-align: baseline; background: transparent;">El Partido Liberal,</i>&nbsp;de M&eacute;xico.</p>
<div id="attachment_1274" class="wp-caption alignright" style="border: 0px; margin-top: 4px; margin-bottom: 20px; margin-left: 24px; padding: 4px; vertical-align: baseline; display: inline; float: right; line-height: 18px; text-align: center; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; width: 188px; max-width: 632px !important; background: rgb(241, 241, 241);"><img class="wp-image-1274" src="http://www.josemarti.cu/wp-content/uploads/2014/06/020-Revista-Venezolana-178x300.jpg" alt="020-Revista-Venezolana" width="178" style="margin-top: 5px; margin-right: 5px; margin-left: 5px; vertical-align: baseline; max-width: 100%; height: auto; background: transparent;" />
<p class="wp-caption-text" style="border: 0px; margin: 5px 5px 24px; vertical-align: baseline; font-family: Arial; color: rgb(136, 136, 136); font-size: 12px; background: transparent;">Solo tuvo dos n&uacute;meros: el 1 de julio de 1881, con treinta dos p&aacute;ginas escritas por el propio Mart&iacute; y el otro, con fecha del 15 de ese mes</p>
</div>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Posteriormente decide buscar mejor acomodo en Venezuela, a donde llega el&nbsp;20 de enero de 1881. Fund&oacute; la&nbsp;<i style="border: 0px; vertical-align: baseline; background: transparent;">Revista Venezolana,</i>&nbsp;de la que pudo editar s&oacute;lo dos n&uacute;meros. Tras chocar con el caudillismo, tiene que retornar a Nueva York.</p>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">A mediados de 1882 reinici&oacute; la labor de reorganizar a los revolucionarios, comunic&aacute;ndoselo mediante cartas a M&aacute;ximo G&oacute;mez y Antonio Maceo. El 2 de octubre de 1884 se re&uacute;ne por vez primera con ambos l&iacute;deres y comienza a colaborar en el Plan Insurreccional G&oacute;mez-Maceo; posteriormente desisti&oacute; de su empe&ntilde;o por estar en desacuerdo con los m&eacute;todos de direcci&oacute;n empleados.</p>
<div id="attachment_1248" class="wp-caption alignleft" style="border: 0px; margin-top: 4px; margin-right: 24px; margin-bottom: 20px; padding: 4px; vertical-align: baseline; display: inline; float: left; line-height: 18px; text-align: center; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; width: 163px; max-width: 632px !important; background: rgb(241, 241, 241);"><a href="http://www.josemarti.cu/wp-content/uploads/2014/06/032-Patria.jpg" class="fancybox" rel="fancybox" style="border: 0px; vertical-align: baseline; color: rgb(4, 87, 169); background: transparent;"><img class="wp-image-1248" src="http://www.josemarti.cu/wp-content/uploads/2014/06/032-Patria-220x300.jpg" alt="032-Patria" width="153" style="border-style: none; margin-top: 5px; margin-right: 5px; margin-left: 5px; vertical-align: baseline; max-width: 100%; height: auto; background: transparent;" /></a>
<p class="wp-caption-text" style="border: 0px; margin: 5px 5px 24px; vertical-align: baseline; font-family: Arial; color: rgb(136, 136, 136); font-size: 12px; background: transparent;">Fundado y dirigido por Jos&eacute; Mart&iacute;, su oficina radicaba en Nueva York. El primer n&uacute;mero sali&oacute; el 14 de marzo de 1892 y desde entonces, hasta diciembre de 1898, en &eacute;l se publicaron importantes trabajos</p>
</div>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">El 30 de noviembre de 1887 fund&oacute; una Comisi&oacute;n Ejecutiva, de la cual fue elegido presidente, encargada de dirigir las actividades organizativas de los revolucionarios. En enero de 1892 redact&oacute; las<i style="border: 0px; vertical-align: baseline; background: transparent;">Bases</i>&nbsp;y los&nbsp;<i style="border: 0px; vertical-align: baseline; background: transparent;">Estatutos del Partido Revolucionario Cubano.</i>&nbsp;El 8 de abril de 1892 result&oacute; electo Delegado de esa organizaci&oacute;n, cuya constituci&oacute;n fue proclamada dos d&iacute;as despu&eacute;s, el 10 de abril de 1892. El 14 de marzo fund&oacute; el peri&oacute;dico&nbsp;<i style="border: 0px; vertical-align: baseline; background: transparent;">Patria,</i>&nbsp;&oacute;rgano oficial del Partido.</p>
<div id="attachment_1333" class="wp-caption alignright" style="border: 0px; margin-top: 4px; margin-bottom: 20px; margin-left: 24px; padding: 4px; vertical-align: baseline; display: inline; float: right; line-height: 18px; text-align: center; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; width: 221px; max-width: 632px !important; background: rgb(241, 241, 241);"><a href="http://www.josemarti.cu/wp-content/uploads/2014/06/038.jpg" class="fancybox" rel="fancybox" style="border: 0px; vertical-align: baseline; color: rgb(4, 87, 169); background: transparent;"><img class="wp-image-1333 size-medium" src="http://www.josemarti.cu/wp-content/uploads/2014/06/038-211x300.jpg" alt="038" width="211" style="border-style: none; margin-top: 5px; margin-right: 5px; margin-left: 5px; vertical-align: baseline; max-width: 100%; height: auto; background: transparent;" /></a>
<p class="wp-caption-text" style="border: 0px; margin: 5px 5px 24px; vertical-align: baseline; font-family: Arial; color: rgb(136, 136, 136); font-size: 12px; background: transparent;">Mart&iacute; y el General G&oacute;mez en New York, 1894.</p>
</div>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">En los a&ntilde;os 1893 y 1894 recorri&oacute; varios pa&iacute;ses de Am&eacute;rica y ciudades de Estados Unidos, uniendo a los principales jefes de la Guerra del 68 y acopiando recursos para la nueva contienda. Desde mediados de 1894 aceler&oacute; los preparativos del Plan Fernandina, con el cual pretend&iacute;a promover una guerra corta, sin grandes desgastes y destrucciones para los cubanos. El 8 de diciembre de 1894 redact&oacute; y firm&oacute;, conjuntamente con los coroneles&nbsp;<i style="border: 0px; vertical-align: baseline; background: transparent;">May&iacute;a</i>Rodr&iacute;guez (en representaci&oacute;n de M&aacute;ximo G&oacute;mez) y Enrique Collazo (en representaci&oacute;n de los patriotas de la Isla), el plan de alzamiento en Cuba. El Plan Fernandina fue descubierto e incautadas las naves con las cuales se iba a ejecutar. A pesar del gran rev&eacute;s que ello signific&oacute;, Mart&iacute; decidi&oacute; seguir adelante con los planes de pronunciamientos armados en la Isla, en lo que fue apoyado por los principales jefes.</p>
<div id="attachment_1524" class="wp-caption alignleft" style="border: 0px; margin-top: 4px; margin-right: 24px; margin-bottom: 20px; padding: 4px; vertical-align: baseline; display: inline; float: left; line-height: 18px; text-align: center; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; width: 280px; max-width: 632px !important; background: rgb(241, 241, 241);"><a href="http://www.josemarti.cu/wp-content/uploads/2014/05/0013-Playita.jpg" class="fancybox" rel="fancybox" style="border: 0px; vertical-align: baseline; color: rgb(4, 87, 169); background: transparent;"><img class="wp-image-1524 size-medium" src="http://www.josemarti.cu/wp-content/uploads/2014/05/0013-Playita-270x300.jpg" alt="Playita" width="270" style="border-style: none; margin-top: 5px; margin-right: 5px; margin-left: 5px; vertical-align: baseline; max-width: 100%; height: auto; background: transparent;" /></a>
<p class="wp-caption-text" style="border: 0px; margin: 5px 5px 24px; vertical-align: baseline; font-family: Arial; color: rgb(136, 136, 136); font-size: 12px; background: transparent;">Lugar donde desembarcaron Jos&eacute; Mart&iacute;, M&aacute;ximo G&oacute;mez y otros patriotas</p>
</div>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">El 29 de enero de 1895, junto con&nbsp;<i style="border: 0px; vertical-align: baseline; background: transparent;">May&iacute;a</i>y Collazo, firm&oacute; la orden de alzamiento y la envi&oacute; a Juan Gualberto G&oacute;mez para su ejecuci&oacute;n. Parti&oacute; de inmediato de Nueva York a Montecristi, en Rep&uacute;blica Dominicana, donde lo esperaba G&oacute;mez, con quien firm&oacute; el 25 de marzo de 1895 un documento conocido como &ldquo;Manifiesto de Montecristi&rdquo;, programa de la nueva guerra. Ambos l&iacute;deres llegan a Cuba el 11 de abril de 1895, por Playitas de Cajobabo, Baracoa.</p>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Tres d&iacute;as despu&eacute;s del desembarco, hicieron contacto con las fuerzas del Comandante F&eacute;lix Ruenes. El 15 de abril de 1895 los jefes all&iacute; reunidos bajo la direcci&oacute;n de G&oacute;mez, acordaron conferir a Mart&iacute; el grado de Mayor General por sus m&eacute;ritos y servicios prestados.</p>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">El 28 de abril de 1895, en el campamento de Vuelta Corta, en Guant&aacute;namo, en uni&oacute;n de G&oacute;mez firm&oacute; la circular &ldquo;Pol&iacute;tica de guerra&rdquo;. Envi&oacute; mensajes a los jefes indic&aacute;ndoles que deb&iacute;an enviar un representante a una asamblea de delegados para elegir un gobierno en breve tiempo. El 5 de mayo de 1895 tuvo lugar su encuentro con G&oacute;mez y Maceo en La Mejorana, donde se discuti&oacute; la estrategia a seguir. El 14 de mayo de 1895 firm&oacute; la &ldquo;Circular a los jefes y oficiales del Ej&eacute;rcito Libertador&rdquo;, &uacute;ltimo de los documentos organizativos de la guerra, la que elabor&oacute; conjuntamente con M&aacute;ximo G&oacute;mez.</p>
<p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Siguiendo la marcha hacia el oeste de la provincia oriental, llegaron a Dos R&iacute;os, cerca de Palma Soriano. El 19 de mayo de 1895 una columna espa&ntilde;ola se despleg&oacute; en la zona y los cubanos fueron a su encuentro. Mart&iacute; marchaba entre G&oacute;mez y el Mayor General Bartolom&eacute; Mas&oacute;.</p>
<div class="clearfix">
  <div  id="attachment_1528" class="wp-caption alignleft" style="border: 0px; margin-top: 4px; margin-right: 24px; margin-bottom: 40px; padding: 4px; vertical-align: baseline; display: inline; float: left; line-height: 18px; text-align: center; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; width: 310px; max-width: 632px !important; background: rgb(241, 241, 241);"><a href="http://www.josemarti.cu/wp-content/uploads/2014/05/0012-Dos-Rios.jpg" class="fancybox" rel="fancybox" style="border: 0px; vertical-align: baseline; color: rgb(4, 87, 169); background: transparent;"><img class="size-medium wp-image-1528" src="http://www.josemarti.cu/wp-content/uploads/2014/05/0012-Dos-Rios-300x218.jpg" alt="Dos R&iacute;os: Lugar donde cae en combate Jos&eacute; Mart&iacute;,  el 19 de mayo de 1895. " width="300" style="border-style: none; margin-top: 5px; margin-right: 5px; margin-left: 5px; vertical-align: baseline; max-width: 100%; height: auto; background: transparent;" /></a>
<p class="wp-caption-text" style="border: 0px; margin: 5px 5px 24px; vertical-align: baseline; font-family: Arial; color: rgb(136, 136, 136); font-size: 12px; background: transparent;">Dos R&iacute;os: Lugar donde cae en combate Jos&eacute; Mart&iacute;,<br />
el 19 de mayo de 1895.</p>
  </div>

  <p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Al llegar al lugar de la acci&oacute;n, G&oacute;mez le indic&oacute; detenerse y permanecer en el lugar acordado. No obstante, en el transcurso del combate, se separ&oacute; del grueso de las fuerzas cubanas, acompa&ntilde;ado solamente por su ayudante &Aacute;ngel de la Guardia. Mart&iacute; cabalg&oacute;, sin saberlo, hacia un grupo de espa&ntilde;oles ocultos en la maleza y fue alcanzado por tres disparos que le provocaron heridas mortales. Cuando se conoci&oacute; lo sucedido, result&oacute; imposible rescatar su cad&aacute;ver, el cual fue conducido por los espa&ntilde;oles y, tras varios enterramientos, fue finalmente sepultado el d&iacute;a 27, en el nicho n&uacute;mero 134 de la galer&iacute;a sur del Cementerio de Santa Ifigenia, en Santiago de Cuba.</p>
  <p style="border: 0px; margin-top: 0px; margin-bottom: 24px; vertical-align: baseline; color: rgb(0, 0, 0); font-family: gl, Arial; font-size: 16px; line-height: 24px; text-align: justify; background: rgb(255, 255, 255);">Fuente:http://www.josemarti.cu/?page_id=102</p>
</div>
  </div>
</div></div> <!-- /node-inner, /node -->
</div>

@endsection